akka.actor.provider = cluster
akka.remote.artery.canonical.hostname = "127.0.0.1"
akka.remote.artery.canonical.port = 2551
akka.cluster.seed-nodes = ["akka://FleetStreamCluster@127.0.0.1:2551"]
akka.cluster.downing-provider-class = "akka.cluster.sbr.SplitBrainResolverProvider"
